version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile-frontend
    ports:
      - "8081:8080"
    environment:
     BACKEND_DNS: backend

  backend:
    build:
      dockerfile: Dockerfile-backend
    environment:
      REDIS_DNS: redis
    networks:
      - redis

  redis:
    image: redis
    networks:
      - backend
    