name: pipeline

# what triggers pipeline?
on:
  push # for testing

#  pull_request:
#   branches: main
    
# what are the user credentials    
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
